name: Coverage

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  coverage:
    name: Codacy coverage
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: '8.1.*'
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: shivammathur/setup-php@2.37.2
        with:
          php-version: '8.4'
          extensions: mbstring, intl
          tools: composer:v2
          coverage: pcov
      - run: composer global config --no-plugins allow-plugins.symfony/flex true
      - run: composer global require --no-progress --no-scripts --no-plugins symfony/flex
      - run: composer update --no-interaction --prefer-dist --with-all-dependencies
      - run: vendor/bin/phpunit --coverage-clover build/coverage.xml
      - name: Upload coverage to Codacy
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/coverage.xml
